# Task 01 on Dataset 3

In [1]:
from sklearn import  preprocessing
from sklearn.naive_bayes import MultinomialNB,GaussianNB
import numpy as np
import pandas as pd

In [6]:
le = preprocessing.LabelEncoder()
dataset = pd.read_csv("Dataset3.csv")
print(dataset)
# print(dataset.iloc[:,:-1].values)

   Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0


In [15]:
feature=dataset.iloc[:,:-1].values
# Class=dataset.iloc[:,0].values
# print(feature[ : ,-1])
feature[ : ,0] = le.fit_transform(feature[ : ,0])
feature[ : ,1] = le.fit_transform(feature[ : ,2])
feature[ : ,2] = le.fit_transform(feature[ : ,2])

print("features\n"+str(feature))
print("class\n"+str(Class))

features
[[1 0 0 1]
 [1 1 1 2]
 [0 0 0 1]
 [1 0 0 1]
 [2 0 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 1]
 [0 0 0 0]
 [2 0 0 2]
 [1 1 1 2]
 [0 1 1 0]
 [0 0 0 1]
 [2 1 1 1]]
class
['R' 'R' 'O' 'R' 'S' 'O' 'O' 'R' 'O' 'S' 'R' 'O' 'O' 'S']


In [5]:
from sklearn.model_selection import train_test_split
data_train,data_test,target_train, target_test = train_test_split(feature,Class, test_size = 0.20, random_state = 166)
#95-5 split is giving all answers as 0 so i tried with other splits 

In [6]:
gnb = GaussianNB()
gnb.fit(data_train,target_train)
target_pred = gnb.predict(data_test)
print(target_pred)

[1 1 1]


In [7]:
from sklearn import metrics
print("Accuracy :",metrics.accuracy_score(target_test, target_pred))

Accuracy : 0.3333333333333333


In [8]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[0, 2],
       [0, 1]], dtype=int64)

In [9]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.3333333333333333
recall: 1.0


In [10]:
q1 = gnb.predict([[1,2,0,1]])
print(q1)
"""
 By manual calculation the ans i get is :
  
"""

[0]


'\n By manual calculation the ans i get is :\n  \n'

In [11]:
q2= gnb.predict([[2,0,1,2]])
print(q2)
"""
 By manual calculation the ans i get is :
  
"""

[1]


'\n By manual calculation the ans i get is :\n  \n'

# Multinomial Naive Bayes

In [12]:
data_train, data_test, target_train, target_test = train_test_split(feature,Class, test_size = 0.20, random_state = 166)
mnb = MultinomialNB()
mnb.fit(data_train,target_train)
target_pred = mnb.predict(data_test)
target_pred

array([1, 1, 1], dtype=int64)

In [13]:
confusion_matrix(target_test, target_pred)

array([[0, 2],
       [0, 1]], dtype=int64)

In [14]:
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.3333333333333333


In [15]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.         0.33333333]
recall: [0. 1.]


c:\users\jainil\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
predict = mnb.predict([[1,2,0,1]])
print(predict)

[1]


In [17]:
predict = mnb.predict([[2,0,1,2]])
print(predict)

[1]
