In [19]:
import numpy as np
import torch

In [20]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [21]:
targets = np.array([[56],
                   [81],
                   [119],
                   [22],
                   [103]],dtype = "float32")
# type(targets)

In [22]:
inputs = torch.from_numpy(inputs)
type(inputs)
targets = torch.from_numpy(targets)
type(targets)

torch.Tensor

# Linear Regression Implementation

In [23]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)
print(weight)
print(bias)


tensor([[ 1.3446,  0.3333, -0.6225],
        [-1.0983,  0.4529,  0.6495]], requires_grad=True)
tensor([-1.8048, -0.7936], requires_grad=True)


In [24]:
inputs@weight.t() + bias

tensor([[ 91.9186, -22.6982],
        [110.0492, -19.3176],
        [123.7397,   2.0112],
        [126.6477, -69.3153],
        [ 79.3990,  12.3652]], grad_fn=<AddBackward0>)

In [27]:
def model(inputs):
    return inputs @ weight.t() + bias
prediction = model(inputs)
prediction


tensor([[ 91.9186, -22.6982],
        [110.0492, -19.3176],
        [123.7397,   2.0112],
        [126.6477, -69.3153],
        [ 79.3990,  12.3652]], grad_fn=<AddBackward0>)

## Loss Finction

In [36]:
# print(prediction)
# print(targets)
dif = prediction - targets
# print(dif)
print(torch.sum(dif*dif) / dif.numel())

tensor(6016.1172, grad_fn=<DivBackward0>)


In [39]:
def MSE(a,b):
    diff = a-b
    return torch.sum(diff*diff) / diff.numel()
mse = MSE(prediction,targets)
mse

tensor(6016.1172, grad_fn=<DivBackward0>)

## Compute Gradients

In [47]:
# mse.backward()
print("Weight grad:\n" , weight.grad)
print("Bias grad:\n" , bias.grad)

Weight grad:
 tensor([[ 2944.6982,  1566.4319,  1179.6901],
        [-8123.9717, -8480.9453, -5262.5605]])
Bias grad:
 tensor([ 30.1509, -95.5909])


## Trainning using gradient descent

In [56]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()

In [57]:
prediction = model(inputs)
mse = MSE(prediction, targets)
mse

tensor(4393.0850, grad_fn=<DivBackward0>)

In [59]:
for i in range(100):
    prediction = model(inputs)
    mse = MSE(prediction, targets)
    mse.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [63]:
prediction = model(inputs)
mse = MSE(prediction, targets)
print("currr mse:\t",mse)
print(prediction)
print(targets)

currr mse:	 tensor(350.9002, grad_fn=<DivBackward0>)
tensor([[ 65.1130,  55.7295],
        [ 79.3303,  83.0142],
        [112.4523, 119.1624],
        [ 68.2048,  13.6829],
        [ 69.0597, 107.4870]], grad_fn=<AddBackward0>)
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
