In [1]:
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from sklearn.preprocessing import LabelEncoder

stopwords = [ "a", "about", "above", "after", "again", "against", "all", "am","an", "and", "any", "are", "as", "at", "be", "because", "been", "before","being", "below", "between", "both", "but", "by", "could", "did", "do","does", "doing", "down", "during", "each", "few", "for", "from", "further","had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here","here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i","i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its","itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on","once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out","over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so","some", "such", "than", "that", "that's", "the", "their", "theirs", "them","themselves", "then", "there", "there's", "these", "they", "they'd","they'll", "they're", "they've", "this", "those", "through", "to", "too","under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're","we've", "were", "what", "what's", "when", "when's", "where", "where's","which", "while", "who", "who's", "whom", "why", "why's", "with", "would","you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself","yourselves" ]

In [2]:
from nltk.tokenize import TweetTokenizer
tokenizer =  TweetTokenizer(preserve_case=True)
ds = pd.read_csv('spam2.csv')
print(ds.info())
ds

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   v1      5572 non-null   object
 1   v2      5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB
None


v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will �_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
changes = {
    'ham' : 1,
    'spam' : 0
}
ds.replace(to_replace=changes,inplace=True,value=None)
ds

v1                                                 v2
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...
...   ..                                                ...
5567   0  This is the 2nd time we have tried 2 contact u...
5568   1              Will �_ b going to esplanade fr home?
5569   1  Pity, * was in mood for that. So...any other s...
5570   1  The guy did some bitching but I acted like i'd...
5571   1                         Rofl. Its true to its name

[5572 rows x 2 columns]

## ---Count Vectoriser---

## Unigram


In [4]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
vectorizer = CountVectorizer(stop_words={'english'})

In [5]:
v1 = vectorizer.fit(ds['v2'])
v1.vocabulary_

{'go': 3538,
 'until': 8005,
 'jurong': 4329,
 'point': 5899,
 'crazy': 2321,
 'available': 1304,
 'only': 5516,
 'in': 4073,
 'bugis': 1751,
 'great': 3622,
 'world': 8462,
 'la': 4455,
 'buffet': 1749,
 'cine': 2044,
 'there': 7621,
 'got': 3582,
 'amore': 1070,
 'wat': 8241,
 'ok': 5483,
 'lar': 4491,
 'joking': 4297,
 'wif': 8365,
 'oni': 5512,
 'free': 3346,
 'entry': 2939,
 'wkly': 8420,
 'comp': 2161,
 'to': 7732,
 'win': 8378,
 'fa': 3076,
 'cup': 2380,
 'final': 3196,
 'tkts': 7719,
 '21st': 411,
 'may': 4910,
 '2005': 402,
 'text': 7573,
 '87121': 784,
 'receive': 6275,
 'question': 6168,
 'std': 7207,
 'txt': 7908,
 'rate': 6220,
 'apply': 1157,
 '08452810075over18': 77,
 'dun': 2793,
 'say': 6610,
 'so': 7002,
 'early': 2814,
 'hor': 3913,
 'already': 1043,
 'then': 7616,
 'nah': 5219,
 'don': 2704,
 'think': 7636,
 'he': 3768,
 'goes': 3546,
 'usf': 8050,
 'lives': 4645,
 'around': 1208,
 'here': 3818,
 'though': 7656,
 'freemsg': 3353,
 'hey': 3828,
 'darling': 2437,
 'it

In [6]:
v1 = vectorizer.transform(ds['v2'])
print(v1.shape)
v1.toarray()[1]

(5572, 8624)


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [7]:
v1= vectorizer.fit_transform(ds['v2'])
v1.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [8]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
mnb = MultinomialNB()

In [9]:
X_train,X_test,y_train,y_test = train_test_split(v1,ds['v1'],random_state=166)

In [10]:
mnb.fit(X_train,y_train)

MultinomialNB()

In [11]:
y_pred_mnb = mnb.predict(X_test)

In [12]:
from sklearn.metrics import precision_score,recall_score
print("Precision Score:", precision_score(y_test,y_pred_mnb))
print("Recall Score:", recall_score(y_test,y_pred_mnb))

Precision Score: 0.9917965545529123
Recall Score: 0.9877450980392157


In [13]:
dtc = DecisionTreeClassifier()
dtc1 = DecisionTreeClassifier()

dtc.fit(X_train,y_train)
dtc1.fit(X_train,y_train)

import numpy as np
# tmp = y_test.to_numpy()
# tmp = tmp.reshape(-1,1)
# print(tmp.shape)
y_dtc = dtc.predict(X_test)
y_dtc1 = dtc1.predict(X_test)

from sklearn.metrics import precision_score,recall_score
print("Precision Score:", precision_score(y_test,y_dtc))
print("Recall Score:", recall_score(y_test,y_dtc))

Precision Score: 0.985172981878089
Recall Score: 0.9771241830065359


In [14]:
## Dtc gives slightly lower recall and precision in unigram

## Bigram

In [15]:
vectorizer1 = CountVectorizer(stop_words={'english'},ngram_range=(2,2))

In [21]:
bigram_v1 = vectorizer1.fit(ds['v2'])
# print(bigram_v1.vocabulary_)
bigram_v1 = vectorizer1.transform(ds['v2'])
bigram_v1.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [22]:
bigram_v1 = vectorizer1.fit_transform(ds['v2'])
X_train,X_test,y_train,y_test = train_test_split(bigram_v1,ds['v1'],random_state=166)

In [23]:
# print(y_pred_bigram-y_pred_mnb)
#Recall score decreases

In [24]:
dtc = DecisionTreeClassifier()
dtc1 = DecisionTreeClassifier()

In [25]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier()

In [26]:
import numpy as np
# tmp = y_test.to_numpy()
# tmp = tmp.reshape(-1,1)
# print(tmp.shape)
y_dtc = dtc.predict(X_test)

In [27]:
from sklearn.metrics import precision_score,recall_score
print("Precision Score:", precision_score(y_test,y_dtc))
print("Recall Score:", recall_score(y_test,y_dtc))

Precision Score: 0.9667194928684627
Recall Score: 0.9967320261437909


In [28]:
mnb = MultinomialNB()
mnb.fit(X_train,y_train)
y_pred_mnb = mnb.predict(X_test)
from sklearn.metrics import precision_score,recall_score
print("Precision Score:", precision_score(y_test,y_pred_mnb))
print("Recall Score:", recall_score(y_test,y_pred_mnb))


Precision Score: 0.9971455756422455
Recall Score: 0.8562091503267973


In [29]:
##Dtr gives better recall while mnb giver better precision in bigram

## ---TFIDF Vectorizer---

In [26]:
#unigram
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer2 = TfidfVectorizer(stop_words={'english'})

In [30]:
tfdif = vectorizer2.fit(ds['v2'])
print(tfdif)
tfdif = vectorizer2.transform(ds['v2'])
tfdif.toarray()
tfdif = vectorizer2.fit_transform(ds['v2'])

TfidfVectorizer(stop_words={'english'})


In [32]:
X_train,X_test,y_train,y_test = train_test_split(tfdif,ds['v1'],random_state=166)

In [33]:
dtc2 = DecisionTreeClassifier()
mnb2 = MultinomialNB()

In [35]:
dtc2.fit(X_train,y_train)
mnb2.fit(X_train,y_train)

MultinomialNB()

In [36]:
tfdif_dt = dtc2.predict(X_test)
tfdif_mnb = mnb2.predict(X_test)

In [37]:
from sklearn.metrics import precision_score,recall_score
print("Precision Score:", precision_score(y_test,tfdif_mnb))
print("Recall Score:", recall_score(y_test,tfdif_mnb))
# tp/tp+fn = 0.96
#recall = 1 !?

Precision Score: 0.9607535321821036
Recall Score: 1.0


In [38]:
from sklearn.metrics import precision_score,recall_score
print("Precision Score:", precision_score(y_test,tfdif_dt))
print("Recall Score:", recall_score(y_test,tfdif_dt))

Precision Score: 0.9779951100244498
Recall Score: 0.9803921568627451


In [40]:
#Precision score for mnb is lower than dtc but recall score is better than dtc

# Bigram

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer2 = TfidfVectorizer(stop_words={'english'},ngram_range=(2,2))

In [42]:
tfdif = vectorizer2.fit(ds['v2'])
print(tfdif)
tfdif = vectorizer2.transform(ds['v2'])
tfdif.toarray()
tfdif = vectorizer2.fit_transform(ds['v2'])

TfidfVectorizer(ngram_range=(2, 2), stop_words={'english'})


In [47]:
X_train,X_test,y_train,y_test = train_test_split(tfdif,ds['v1'],random_state=166)
dtc2 = DecisionTreeClassifier()
mnb2 = MultinomialNB()

dtc2.fit(X_train,y_train)
mnb2.fit(X_train,y_train)
tfdif_dt = dtc2.predict(X_test)
tfdif_mnb = mnb2.predict(X_test)

print("MNB")
from sklearn.metrics import precision_score,recall_score
print("Precision Score:", precision_score(y_test,tfdif_mnb))
print("Recall Score:", recall_score(y_test,tfdif_mnb))
print("DTC")
from sklearn.metrics import precision_score,recall_score
print("Precision Score:", precision_score(y_test,tfdif_dt))
print("Recall Score:", recall_score(y_test,tfdif_dt))

MNB
Precision Score: 0.9400921658986175
Recall Score: 1.0
DTC
Precision Score: 0.9674085850556439
Recall Score: 0.994281045751634


In [44]:
## precisoin score is lesser than unigram in both 
## recall is slighty higher in mnb compared to dtc